/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ATMSystemBranch;

/**
 *
 * @author yan
 */
public class ATMWindow extends javax.swing.JFrame {

    /**
     * Creates new form ATMWindow
     */
    private String acctNum;
    private String pin;
    private int balance;
    
    private String depositNumber = "";
    public ATMWindow(String acctNum, String pin, int balance) {
        initComponents();
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
        this.acctNum = acctNum;
        this.pin = pin;
        this.balance = balance;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ATMHomepage = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ButtonBalanceInquiry = new javax.swing.JButton();
        ButtonDeposit = new javax.swing.JButton();
        ButtonWithdraw = new javax.swing.JButton();
        ButtonTransfer = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        HomepageBG = new javax.swing.JLabel();
        WithdrawCash = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        withdrawField = new javax.swing.JTextField();
        keypadPanel = new javax.swing.JPanel();
        keyButton1 = new javax.swing.JButton();
        keyButton2 = new javax.swing.JButton();
        keyButton3 = new javax.swing.JButton();
        keyButton4 = new javax.swing.JButton();
        keyButton5 = new javax.swing.JButton();
        keyButton6 = new javax.swing.JButton();
        keyButton7 = new javax.swing.JButton();
        keyButton8 = new javax.swing.JButton();
        keyButton9 = new javax.swing.JButton();
        keyButtonX = new javax.swing.JButton();
        keyButton0 = new javax.swing.JButton();
        keyButtonOK = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();
        BackWithdraw = new javax.swing.JButton();
        WithdrawBG = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        TransferCash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        transferBackButton = new javax.swing.JButton();
        TransferBG = new javax.swing.JLabel();
        DepositCash = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        depositKeypad = new javax.swing.JPanel();
        depKey1 = new javax.swing.JButton();
        depKey2 = new javax.swing.JButton();
        depKey3 = new javax.swing.JButton();
        depKey4 = new javax.swing.JButton();
        depKey5 = new javax.swing.JButton();
        depKey6 = new javax.swing.JButton();
        depKey7 = new javax.swing.JButton();
        depKey8 = new javax.swing.JButton();
        depKey9 = new javax.swing.JButton();
        depKeyX = new javax.swing.JButton();
        depKey0 = new javax.swing.JButton();
        depKeyOK = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        depositBackButton = new javax.swing.JButton();
        DepositBG = new javax.swing.JLabel();
        BalanceCheck = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        DisplayBalance = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PrintBalance = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        balanceBackButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ATMHomepage.setBackground(new java.awt.Color(102, 204, 255));
        ATMHomepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        balanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(51, 204, 255));
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceLabel.setText("Balance Inquiry");
        balanceLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(balanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 175, 281, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 204, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Deposit");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 295, 281, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Withdraw");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 175, 280, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Transfer");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 295, 280, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 204, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Back");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 404, 280, -1));

        ButtonBalanceInquiry.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonBalanceInquiry.setText("1");
        ButtonBalanceInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBalanceInquiryActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonBalanceInquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 75, 52));

        ButtonDeposit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonDeposit.setText("2");
        ButtonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDepositActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 295, 75, 52));

        ButtonWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonWithdraw.setText("3");
        ButtonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWithdrawActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 175, 75, 52));

        ButtonTransfer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonTransfer.setText("4");
        ButtonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransferActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 295, 75, 52));

        ButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonBack.setText("5");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 404, 75, 52));

        HomepageBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        ATMHomepage.add(HomepageBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        MainPanel.add(ATMHomepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        WithdrawCash.setBackground(new java.awt.Color(255, 255, 204));
        WithdrawCash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WITHDRAW CASH");
        WithdrawCash.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 320, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Amount");
        WithdrawCash.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 311, -1));

        withdrawField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WithdrawCash.add(withdrawField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 310, -1));

        keypadPanel.setOpaque(false);
        keypadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keyButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton1.setText("1");
        keypadPanel.add(keyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 17, 75, 50));

        keyButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton2.setText("2");
        keypadPanel.add(keyButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 17, 75, 50));

        keyButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton3.setText("3");
        keypadPanel.add(keyButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 17, 75, 50));

        keyButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton4.setText("4");
        keypadPanel.add(keyButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 85, 75, 50));

        keyButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton5.setText("5");
        keypadPanel.add(keyButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 85, 75, 50));

        keyButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton6.setText("6");
        keypadPanel.add(keyButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 85, 75, 50));

        keyButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton7.setText("7");
        keypadPanel.add(keyButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 153, 75, 50));

        keyButton8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton8.setText("8");
        keypadPanel.add(keyButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 153, 75, 50));

        keyButton9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton9.setText("9");
        keypadPanel.add(keyButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 153, 75, 50));

        keyButtonX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButtonX.setText("X");
        keypadPanel.add(keyButtonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 221, 75, 50));

        keyButton0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButton0.setText("0");
        keypadPanel.add(keyButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 221, 75, 50));

        keyButtonOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        keyButtonOK.setText("OK");
        keypadPanel.add(keyButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 221, 75, 50));

        WithdrawCash.add(keypadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 311, 300));

        backLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        backLabel.setForeground(new java.awt.Color(51, 204, 255));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("Back");
        backLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        WithdrawCash.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 100, 50));

        BackWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackWithdraw.setText("1");
        BackWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackWithdrawActionPerformed(evt);
            }
        });
        WithdrawCash.add(BackWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 75, 50));

        WithdrawBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        WithdrawCash.add(WithdrawBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(WithdrawCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        headerPanel.setBackground(new java.awt.Color(204, 255, 204));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        headerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QuPAL BANKING Title.png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(headerLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        TransferCash.setBackground(new java.awt.Color(255, 102, 102));
        TransferCash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSFER CASH");
        TransferCash.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 39, 300, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Amount");
        TransferCash.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 300, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TransferCash.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 167, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Account Number");
        TransferCash.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 300, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TransferCash.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 300, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("1");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, 75, 50));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("2");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 19, 75, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("3");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 19, 75, 50));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("4");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 87, 75, 50));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setText("5");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 87, 75, 50));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setText("6");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 87, 75, 50));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton7.setText("7");
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 155, 75, 50));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton8.setText("8");
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 155, 75, 50));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton9.setText("9");
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 155, 75, 50));

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton10.setText("X");
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 223, 75, 50));

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton11.setText("0");
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 223, 75, 50));

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton12.setText("OK");
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 223, 75, 50));

        TransferCash.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 329, 300, 296));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Back");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        TransferCash.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 553, 113, -1));

        transferBackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transferBackButton.setText("1");
        transferBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferBackButtonMouseClicked(evt);
            }
        });
        transferBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBackButtonActionPerformed(evt);
            }
        });
        TransferCash.add(transferBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 553, 75, 52));

        TransferBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        TransferCash.add(TransferBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(TransferCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        DepositCash.setBackground(new java.awt.Color(255, 204, 204));
        DepositCash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DEPOSIT CASH");
        DepositCash.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 39, 300, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter Amount");
        DepositCash.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 268, -1));

        depositField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DepositCash.add(depositField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 282, -1));

        depositKeypad.setOpaque(false);
        depositKeypad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depKey1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey1.setText("1");
        depKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey1ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, 75, 50));

        depKey2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey2.setText("2");
        depKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey2ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 21, 75, 50));

        depKey3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey3.setText("3");
        depKey3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey3ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 21, 75, 50));

        depKey4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey4.setText("4");
        depKey4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey4ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 89, 75, 50));

        depKey5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey5.setText("5");
        depKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey5ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey5, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 89, 75, 50));

        depKey6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey6.setText("6");
        depKey6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey6ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey6, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 89, 75, 50));

        depKey7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey7.setText("7");
        depKey7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey7ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 157, 75, 50));

        depKey8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey8.setText("8");
        depKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey8ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey8, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 157, 76, 50));

        depKey9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey9.setText("9");
        depKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey9ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey9, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 157, 75, 50));

        depKeyX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKeyX.setText("<--");
        depKeyX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKeyXActionPerformed(evt);
            }
        });
        depositKeypad.add(depKeyX, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 225, 75, 50));

        depKey0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey0.setText("0");
        depKey0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey0ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey0, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 225, 76, 50));

        depKeyOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKeyOK.setText("OK");
        depositKeypad.add(depKeyOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 225, 75, 50));

        DepositCash.add(depositKeypad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 282, 300));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Back");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        DepositCash.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 100, 50));

        depositBackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        depositBackButton.setText("1");
        depositBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositBackButtonMouseClicked(evt);
            }
        });
        depositBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBackButtonActionPerformed(evt);
            }
        });
        DepositCash.add(depositBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 75, 50));

        DepositBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        DepositCash.add(DepositBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(DepositCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        BalanceCheck.setBackground(new java.awt.Color(204, 204, 255));
        BalanceCheck.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CURRENT BALANCE");
        BalanceCheck.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 39, 360, -1));

        DisplayBalance.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        DisplayBalance.setForeground(new java.awt.Color(255, 255, 255));
        DisplayBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DisplayBalance.setText("00");
        BalanceCheck.add(DisplayBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 194, 340, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Print");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        BalanceCheck.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 392, 231, -1));

        PrintBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PrintBalance.setText("1");
        BalanceCheck.add(PrintBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 392, 75, 52));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Back");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        BalanceCheck.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 392, 231, -1));

        balanceBackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        balanceBackButton.setText("2");
        balanceBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balanceBackButtonMouseClicked(evt);
            }
        });
        balanceBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBackButtonActionPerformed(evt);
            }
        });
        BalanceCheck.add(balanceBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 394, 75, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        BalanceCheck.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(BalanceCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void balanceBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBackButtonMouseClicked
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_balanceBackButtonMouseClicked

    private void depositBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBackButtonMouseClicked
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_depositBackButtonMouseClicked

    private void transferBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferBackButtonMouseClicked
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_transferBackButtonMouseClicked

    private void BackWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackWithdrawActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_BackWithdrawActionPerformed

    private void ButtonBalanceInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBalanceInquiryActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(true);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
        showCurrentBalance(balance);
    }//GEN-LAST:event_ButtonBalanceInquiryActionPerformed

    private void ButtonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDepositActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(true);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
        depositNumber = "";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_ButtonDepositActionPerformed

    private void ButtonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWithdrawActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(true);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_ButtonWithdrawActionPerformed

    private void ButtonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransferActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(true);
    }//GEN-LAST:event_ButtonTransferActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
        returnToPin();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void transferBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBackButtonActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_transferBackButtonActionPerformed

    private void depositBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBackButtonActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_depositBackButtonActionPerformed

    private void balanceBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBackButtonActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferCash.setVisible(false);
    }//GEN-LAST:event_balanceBackButtonActionPerformed

    private void depKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey1ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "1";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey1ActionPerformed

    private void depKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey2ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "2";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey2ActionPerformed

    private void depKey4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey4ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "4";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey4ActionPerformed

    private void depKey3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey3ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "3";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey3ActionPerformed

    private void depKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey5ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "5";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey5ActionPerformed

    private void depKey6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey6ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "6";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey6ActionPerformed

    private void depKey7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey7ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "7";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey7ActionPerformed

    private void depKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey8ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "8";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey8ActionPerformed

    private void depKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey9ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "9";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey9ActionPerformed

    private void depKey0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey0ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "0";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey0ActionPerformed

    private void depKeyXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKeyXActionPerformed
        // TODO add your handling code here:
        if ("".equals(depositNumber)){
            return;
        }else{
            depositNumber = depositNumber.substring(0, depositNumber.length() - 1);
            depositField.setText(depositNumber);
        }
    }//GEN-LAST:event_depKeyXActionPerformed

    // </editor-fold>   
    
    private void showCurrentBalance(int balance){
        System.out.println(balance);
        String balanceDisplay = Integer.toString(balance);
        DisplayBalance.setText(balanceDisplay);
    }
    private void deposit(int balance){
        
    }
    private void returnToPin(){
        PinWindow pin = new PinWindow();
        pin.setVisible(true);
        setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new ATMWindow().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ATMHomepage;
    private javax.swing.JButton BackWithdraw;
    private javax.swing.JPanel BalanceCheck;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonBalanceInquiry;
    private javax.swing.JButton ButtonDeposit;
    private javax.swing.JButton ButtonTransfer;
    private javax.swing.JButton ButtonWithdraw;
    private javax.swing.JLabel DepositBG;
    private javax.swing.JPanel DepositCash;
    private javax.swing.JLabel DisplayBalance;
    private javax.swing.JLabel HomepageBG;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton PrintBalance;
    private javax.swing.JLabel TransferBG;
    private javax.swing.JPanel TransferCash;
    private javax.swing.JLabel WithdrawBG;
    private javax.swing.JPanel WithdrawCash;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton balanceBackButton;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton depKey0;
    private javax.swing.JButton depKey1;
    private javax.swing.JButton depKey2;
    private javax.swing.JButton depKey3;
    private javax.swing.JButton depKey4;
    private javax.swing.JButton depKey5;
    private javax.swing.JButton depKey6;
    private javax.swing.JButton depKey7;
    private javax.swing.JButton depKey8;
    private javax.swing.JButton depKey9;
    private javax.swing.JButton depKeyOK;
    private javax.swing.JButton depKeyX;
    private javax.swing.JButton depositBackButton;
    private javax.swing.JTextField depositField;
    private javax.swing.JPanel depositKeypad;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton keyButton0;
    private javax.swing.JButton keyButton1;
    private javax.swing.JButton keyButton2;
    private javax.swing.JButton keyButton3;
    private javax.swing.JButton keyButton4;
    private javax.swing.JButton keyButton5;
    private javax.swing.JButton keyButton6;
    private javax.swing.JButton keyButton7;
    private javax.swing.JButton keyButton8;
    private javax.swing.JButton keyButton9;
    private javax.swing.JButton keyButtonOK;
    private javax.swing.JButton keyButtonX;
    private javax.swing.JPanel keypadPanel;
    private javax.swing.JButton transferBackButton;
    private javax.swing.JTextField withdrawField;
    // End of variables declaration//GEN-END:variables
}
