/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ATMSystemBranch;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yan
 */
public class ATMWindow extends javax.swing.JFrame {

    /**
     * Creates new form ATMWindow
     */
    private String username;
    private String password;
    private String name;
    private String birthdate;
    private String phoneNumber;
    private String address;
    private String accNumber;
    private String type;
    private String card;
    private String pin;
    private int balance;
    private int reserve;
    
    private String depositNumber = "";
    private String withdrawNumber = "";
    private String transferAmountNumber = "";
    private String transferAccountNumber = "";
    public ATMWindow(String username,
            String password,
            String name,
            String birthdate,
            String phoneNumber,
            String address, 
            String accNumber,
            String type,
            String card, 
            String pin, 
            int balance) {
        
        initComponents();
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
        this.username = username;
        this.password = password;
        this.name = name;
        this.birthdate = birthdate;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.accNumber = accNumber;
        this.type = type;
        this.card = card;
        this.pin = pin;
        this.balance = balance;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ATMHomepage = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ButtonBalanceInquiry = new javax.swing.JButton();
        ButtonDeposit = new javax.swing.JButton();
        ButtonWithdraw = new javax.swing.JButton();
        ButtonTransfer = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        HomepageBG = new javax.swing.JLabel();
        WithdrawCash = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        withdrawField = new javax.swing.JTextField();
        keypadPanel = new javax.swing.JPanel();
        witKey1 = new javax.swing.JButton();
        witKey2 = new javax.swing.JButton();
        witKey3 = new javax.swing.JButton();
        witKey4 = new javax.swing.JButton();
        witKey5 = new javax.swing.JButton();
        witKey6 = new javax.swing.JButton();
        witKey7 = new javax.swing.JButton();
        witKey8 = new javax.swing.JButton();
        witKey9 = new javax.swing.JButton();
        witKeyX = new javax.swing.JButton();
        witKey0 = new javax.swing.JButton();
        witKeyOK = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();
        BackWithdraw = new javax.swing.JButton();
        WithdrawBG = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        TransferAmount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        transferAmountField = new javax.swing.JTextField();
        transAmntKeypad = new javax.swing.JPanel();
        transAmtKey1 = new javax.swing.JButton();
        transAmtKey2 = new javax.swing.JButton();
        transAmtKey3 = new javax.swing.JButton();
        transAmtKey4 = new javax.swing.JButton();
        transAmtKey5 = new javax.swing.JButton();
        transAmtKey6 = new javax.swing.JButton();
        transAmtKey7 = new javax.swing.JButton();
        transAmtKey8 = new javax.swing.JButton();
        transAmtKey9 = new javax.swing.JButton();
        transAmtKeyX = new javax.swing.JButton();
        transAmtKey0 = new javax.swing.JButton();
        transAmtKeyOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        transAmtBack = new javax.swing.JButton();
        TransferBG = new javax.swing.JLabel();
        TransferAccount = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        transferAccountField = new javax.swing.JTextField();
        transferAccountKeypad = new javax.swing.JPanel();
        transAccKey1 = new javax.swing.JButton();
        transAccKey2 = new javax.swing.JButton();
        transAccKey3 = new javax.swing.JButton();
        transAccKey4 = new javax.swing.JButton();
        transAccKey5 = new javax.swing.JButton();
        transAccKey6 = new javax.swing.JButton();
        transAccKey7 = new javax.swing.JButton();
        transAccKey8 = new javax.swing.JButton();
        transAccKey9 = new javax.swing.JButton();
        transAccKeyX = new javax.swing.JButton();
        transAccKey0 = new javax.swing.JButton();
        transAccKeyOK = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        transAccBack = new javax.swing.JButton();
        TransferBG1 = new javax.swing.JLabel();
        DepositCash = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        depositKeypad = new javax.swing.JPanel();
        depKey1 = new javax.swing.JButton();
        depKey2 = new javax.swing.JButton();
        depKey3 = new javax.swing.JButton();
        depKey4 = new javax.swing.JButton();
        depKey5 = new javax.swing.JButton();
        depKey6 = new javax.swing.JButton();
        depKey7 = new javax.swing.JButton();
        depKey8 = new javax.swing.JButton();
        depKey9 = new javax.swing.JButton();
        depKeyX = new javax.swing.JButton();
        depKey0 = new javax.swing.JButton();
        depKeyOK = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        depositBackButton = new javax.swing.JButton();
        DepositBG = new javax.swing.JLabel();
        BalanceCheck = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        DisplayBalance = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PrintBalance = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        balanceBackButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ATMHomepage.setBackground(new java.awt.Color(102, 204, 255));
        ATMHomepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        balanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(51, 204, 255));
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceLabel.setText("Balance Inquiry");
        balanceLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(balanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 175, 281, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 204, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Deposit");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 295, 281, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Withdraw");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 175, 280, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Transfer");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 295, 280, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 204, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Back");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ATMHomepage.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 404, 280, -1));

        ButtonBalanceInquiry.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonBalanceInquiry.setText("1");
        ButtonBalanceInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBalanceInquiryActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonBalanceInquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 75, 52));

        ButtonDeposit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonDeposit.setText("2");
        ButtonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDepositActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 295, 75, 52));

        ButtonWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonWithdraw.setText("3");
        ButtonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWithdrawActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 175, 75, 52));

        ButtonTransfer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonTransfer.setText("4");
        ButtonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransferActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 295, 75, 52));

        ButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonBack.setText("5");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        ATMHomepage.add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 404, 75, 52));

        HomepageBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        ATMHomepage.add(HomepageBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        MainPanel.add(ATMHomepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        WithdrawCash.setBackground(new java.awt.Color(255, 255, 204));
        WithdrawCash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WITHDRAW CASH");
        WithdrawCash.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 320, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Amount");
        WithdrawCash.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 311, -1));

        withdrawField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WithdrawCash.add(withdrawField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 310, -1));

        keypadPanel.setOpaque(false);
        keypadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        witKey1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey1.setText("1");
        witKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey1ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 17, 75, 50));

        witKey2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey2.setText("2");
        witKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey2ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 17, 75, 50));

        witKey3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey3.setText("3");
        witKey3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey3ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 17, 75, 50));

        witKey4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey4.setText("4");
        witKey4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey4ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 85, 75, 50));

        witKey5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey5.setText("5");
        witKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey5ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 85, 75, 50));

        witKey6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey6.setText("6");
        witKey6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey6ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 85, 75, 50));

        witKey7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey7.setText("7");
        witKey7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey7ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 153, 75, 50));

        witKey8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey8.setText("8");
        witKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey8ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey8, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 153, 75, 50));

        witKey9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey9.setText("9");
        witKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey9ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey9, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 153, 75, 50));

        witKeyX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKeyX.setText("<--");
        witKeyX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKeyXActionPerformed(evt);
            }
        });
        keypadPanel.add(witKeyX, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 221, 75, 50));

        witKey0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKey0.setText("0");
        witKey0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKey0ActionPerformed(evt);
            }
        });
        keypadPanel.add(witKey0, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 221, 75, 50));

        witKeyOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        witKeyOK.setText("OK");
        witKeyOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                witKeyOKActionPerformed(evt);
            }
        });
        keypadPanel.add(witKeyOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 221, 75, 50));

        WithdrawCash.add(keypadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 311, 300));

        backLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        backLabel.setForeground(new java.awt.Color(51, 204, 255));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("Back");
        backLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        WithdrawCash.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 100, 50));

        BackWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackWithdraw.setText("1");
        BackWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackWithdrawActionPerformed(evt);
            }
        });
        WithdrawCash.add(BackWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 75, 50));

        WithdrawBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        WithdrawCash.add(WithdrawBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(WithdrawCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        headerPanel.setBackground(new java.awt.Color(204, 255, 204));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        headerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QuPAL BANKING Title.png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(headerLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        TransferAmount.setBackground(new java.awt.Color(255, 102, 102));
        TransferAmount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSFER CASH");
        TransferAmount.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 39, 300, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Amount");
        TransferAmount.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 300, -1));

        transferAmountField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TransferAmount.add(transferAmountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 167, 300, -1));

        transAmntKeypad.setOpaque(false);
        transAmntKeypad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transAmtKey1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey1.setText("1");
        transAmtKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey1ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, 75, 50));

        transAmtKey2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey2.setText("2");
        transAmtKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey2ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 19, 75, 50));

        transAmtKey3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey3.setText("3");
        transAmtKey3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey3ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 19, 75, 50));

        transAmtKey4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey4.setText("4");
        transAmtKey4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey4ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 87, 75, 50));

        transAmtKey5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey5.setText("5");
        transAmtKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey5ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 87, 75, 50));

        transAmtKey6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey6.setText("6");
        transAmtKey6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey6ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey6, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 87, 75, 50));

        transAmtKey7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey7.setText("7");
        transAmtKey7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey7ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 155, 75, 50));

        transAmtKey8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey8.setText("8");
        transAmtKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey8ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 155, 75, 50));

        transAmtKey9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey9.setText("9");
        transAmtKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey9ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey9, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 155, 75, 50));

        transAmtKeyX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKeyX.setText("<--");
        transAmtKeyX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKeyXActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKeyX, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 223, 75, 50));

        transAmtKey0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKey0.setText("0");
        transAmtKey0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKey0ActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKey0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 223, 75, 50));

        transAmtKeyOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAmtKeyOK.setText("OK");
        transAmtKeyOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtKeyOKActionPerformed(evt);
            }
        });
        transAmntKeypad.add(transAmtKeyOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 223, 75, 50));

        TransferAmount.add(transAmntKeypad, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 329, 300, 296));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Back");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        TransferAmount.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 553, 113, -1));

        transAmtBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transAmtBack.setText("1");
        transAmtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transAmtBackMouseClicked(evt);
            }
        });
        transAmtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAmtBackActionPerformed(evt);
            }
        });
        TransferAmount.add(transAmtBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 553, 75, 52));

        TransferBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        TransferAmount.add(TransferBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(TransferAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        TransferAccount.setBackground(new java.awt.Color(255, 102, 102));
        TransferAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TRANSFER CASH");
        TransferAccount.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 39, 300, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Enter Account Number");
        TransferAccount.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 300, -1));

        transferAccountField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TransferAccount.add(transferAccountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 300, -1));

        transferAccountKeypad.setOpaque(false);
        transferAccountKeypad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transAccKey1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey1.setText("1");
        transAccKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey1ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, 75, 50));

        transAccKey2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey2.setText("2");
        transAccKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey2ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 19, 75, 50));

        transAccKey3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey3.setText("3");
        transAccKey3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey3ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 19, 75, 50));

        transAccKey4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey4.setText("4");
        transAccKey4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey4ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 87, 75, 50));

        transAccKey5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey5.setText("5");
        transAccKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey5ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 87, 75, 50));

        transAccKey6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey6.setText("6");
        transAccKey6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey6ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey6, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 87, 75, 50));

        transAccKey7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey7.setText("7");
        transAccKey7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey7ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 155, 75, 50));

        transAccKey8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey8.setText("8");
        transAccKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey8ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 155, 75, 50));

        transAccKey9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey9.setText("9");
        transAccKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey9ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey9, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 155, 75, 50));

        transAccKeyX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKeyX.setText("<--");
        transAccKeyX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKeyXActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKeyX, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 223, 75, 50));

        transAccKey0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKey0.setText("0");
        transAccKey0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKey0ActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKey0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 223, 75, 50));

        transAccKeyOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transAccKeyOK.setText("OK");
        transAccKeyOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccKeyOKActionPerformed(evt);
            }
        });
        transferAccountKeypad.add(transAccKeyOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 223, 75, 50));

        TransferAccount.add(transferAccountKeypad, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 329, 300, 296));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 204, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Back");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        TransferAccount.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 553, 113, -1));

        transAccBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transAccBack.setText("1");
        transAccBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transAccBackMouseClicked(evt);
            }
        });
        transAccBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transAccBackActionPerformed(evt);
            }
        });
        TransferAccount.add(transAccBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 553, 75, 52));

        TransferBG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        TransferAccount.add(TransferBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(TransferAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        DepositCash.setBackground(new java.awt.Color(255, 204, 204));
        DepositCash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DEPOSIT CASH");
        DepositCash.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 39, 300, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter Amount");
        DepositCash.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 268, -1));

        depositField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DepositCash.add(depositField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 282, -1));

        depositKeypad.setOpaque(false);
        depositKeypad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depKey1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey1.setText("1");
        depKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey1ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, 75, 50));

        depKey2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey2.setText("2");
        depKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey2ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 21, 75, 50));

        depKey3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey3.setText("3");
        depKey3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey3ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 21, 75, 50));

        depKey4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey4.setText("4");
        depKey4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey4ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 89, 75, 50));

        depKey5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey5.setText("5");
        depKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey5ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey5, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 89, 75, 50));

        depKey6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey6.setText("6");
        depKey6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey6ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey6, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 89, 75, 50));

        depKey7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey7.setText("7");
        depKey7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey7ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 157, 75, 50));

        depKey8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey8.setText("8");
        depKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey8ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey8, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 157, 76, 50));

        depKey9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey9.setText("9");
        depKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey9ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey9, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 157, 75, 50));

        depKeyX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKeyX.setText("<--");
        depKeyX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKeyXActionPerformed(evt);
            }
        });
        depositKeypad.add(depKeyX, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 225, 75, 50));

        depKey0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKey0.setText("0");
        depKey0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKey0ActionPerformed(evt);
            }
        });
        depositKeypad.add(depKey0, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 225, 76, 50));

        depKeyOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        depKeyOK.setText("OK");
        depKeyOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depKeyOKActionPerformed(evt);
            }
        });
        depositKeypad.add(depKeyOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 225, 75, 50));

        DepositCash.add(depositKeypad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 282, 300));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Back");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        DepositCash.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 100, 50));

        depositBackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        depositBackButton.setText("1");
        depositBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositBackButtonMouseClicked(evt);
            }
        });
        depositBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBackButtonActionPerformed(evt);
            }
        });
        DepositCash.add(depositBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 75, 50));

        DepositBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        DepositCash.add(DepositBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(DepositCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        BalanceCheck.setBackground(new java.awt.Color(204, 204, 255));
        BalanceCheck.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CURRENT BALANCE");
        BalanceCheck.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 39, 360, -1));

        DisplayBalance.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        DisplayBalance.setForeground(new java.awt.Color(255, 255, 255));
        DisplayBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DisplayBalance.setText("00");
        BalanceCheck.add(DisplayBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 194, 340, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Print");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        BalanceCheck.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 392, 231, -1));

        PrintBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PrintBalance.setText("1");
        BalanceCheck.add(PrintBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 392, 75, 52));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Back");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        BalanceCheck.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 392, 231, -1));

        balanceBackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        balanceBackButton.setText("2");
        balanceBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balanceBackButtonMouseClicked(evt);
            }
        });
        balanceBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBackButtonActionPerformed(evt);
            }
        });
        BalanceCheck.add(balanceBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 394, 75, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATMPanel_BG.png"))); // NOI18N
        BalanceCheck.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        MainPanel.add(BalanceCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">
    
    // <editor-fold defaultstate="collapsed" desc="Panel Buttons">
    private void balanceBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBackButtonMouseClicked
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_balanceBackButtonMouseClicked

    private void depositBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBackButtonMouseClicked
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_depositBackButtonMouseClicked

    private void transAmtBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transAmtBackMouseClicked
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_transAmtBackMouseClicked

    private void BackWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackWithdrawActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_BackWithdrawActionPerformed

    private void ButtonBalanceInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBalanceInquiryActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(true);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
        showCurrentBalance(balance);
    }//GEN-LAST:event_ButtonBalanceInquiryActionPerformed

    private void ButtonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDepositActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(true);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
        depositNumber = "";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_ButtonDepositActionPerformed

    private void ButtonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWithdrawActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(true);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
        withdrawNumber = "";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_ButtonWithdrawActionPerformed

    private void ButtonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransferActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(false);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(true);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_ButtonTransferActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
        returnToPin();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void transAmtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtBackActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_transAmtBackActionPerformed

    private void depositBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBackButtonActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_depositBackButtonActionPerformed

    private void balanceBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBackButtonActionPerformed
        // TODO add your handling code here:
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }//GEN-LAST:event_balanceBackButtonActionPerformed

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Deposit Key Buttons">
    private void depKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey1ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "1";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey1ActionPerformed

    private void depKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey2ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "2";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey2ActionPerformed

    private void depKey4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey4ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "4";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey4ActionPerformed

    private void depKey3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey3ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "3";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey3ActionPerformed

    private void depKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey5ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "5";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey5ActionPerformed

    private void depKey6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey6ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "6";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey6ActionPerformed

    private void depKey7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey7ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "7";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey7ActionPerformed

    private void depKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey8ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "8";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey8ActionPerformed

    private void depKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey9ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "9";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey9ActionPerformed

    private void depKey0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKey0ActionPerformed
        // TODO add your handling code here:
        depositNumber = depositNumber+ "0";
        depositField.setText(depositNumber);
    }//GEN-LAST:event_depKey0ActionPerformed

    private void depKeyXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKeyXActionPerformed
        // TODO add your handling code here:
        if ("".equals(depositNumber)){
            
        }else{
            depositNumber = depositNumber.substring(0, depositNumber.length() - 1);
            depositField.setText(depositNumber);
        }
    }//GEN-LAST:event_depKeyXActionPerformed

    private void depKeyOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depKeyOKActionPerformed
        // TODO add your handling code here:
        deleteLine(accNumber);
        deposit(balance);
    }//GEN-LAST:event_depKeyOKActionPerformed

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Withdraw Key Buttons">
    private void witKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey1ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "1";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey1ActionPerformed

    private void witKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey2ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "2";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey2ActionPerformed

    private void witKey3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey3ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "3";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey3ActionPerformed

    private void witKey4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey4ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "4";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey4ActionPerformed

    private void witKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey5ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "5";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey5ActionPerformed

    private void witKey6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey6ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "6";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey6ActionPerformed

    private void witKey7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey7ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "7";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey7ActionPerformed

    private void witKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey8ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "8";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey8ActionPerformed

    private void witKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey9ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "9";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey9ActionPerformed

    private void witKey0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKey0ActionPerformed
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "0";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_witKey0ActionPerformed

    private void witKeyXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKeyXActionPerformed
        // TODO add your handling code here:
        if ("".equals(withdrawNumber)){
            
        }else{
            withdrawNumber = withdrawNumber.substring(0, withdrawNumber.length() - 1);
            withdrawField.setText(withdrawNumber);
        }
    }//GEN-LAST:event_witKeyXActionPerformed

    private void witKeyOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_witKeyOKActionPerformed
        // TODO add your handling code here:
        deleteLine(accNumber);
        withdraw(balance);
    }//GEN-LAST:event_witKeyOKActionPerformed

    private void transAccBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transAccBackMouseClicked
        // TODO add your handling code here:
        withdrawNumber = withdrawNumber+ "9";
        withdrawField.setText(withdrawNumber);
    }//GEN-LAST:event_transAccBackMouseClicked
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Transfer Amount Key">
    private void transAmtKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey1ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "1";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey1ActionPerformed

    private void transAmtKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey2ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "2";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey2ActionPerformed

    private void transAmtKey3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey3ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "3";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey3ActionPerformed

    private void transAmtKey4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey4ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "4";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey4ActionPerformed

    private void transAmtKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey5ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "5";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey5ActionPerformed

    private void transAmtKey6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey6ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "6";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey6ActionPerformed

    private void transAmtKey7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey7ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "7";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey7ActionPerformed

    private void transAmtKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey8ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "8";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey8ActionPerformed

    private void transAmtKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey9ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "9";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey9ActionPerformed

    private void transAmtKey0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKey0ActionPerformed
        // TODO add your handling code here:
        transferAmountNumber = transferAmountNumber+ "0";
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAmtKey0ActionPerformed

    private void transAmtKeyXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKeyXActionPerformed
        // TODO add your handling code here:
        if ("".equals(transferAmountNumber)){
            
        }else{
            transferAmountNumber = transferAmountNumber.substring(0, transferAmountNumber.length() - 1);
            transferAmountField.setText(transferAmountNumber);
        }
    }//GEN-LAST:event_transAmtKeyXActionPerformed

    private void transAmtKeyOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAmtKeyOKActionPerformed
        // TODO add your handling code here:
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(true);
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAmtKeyOKActionPerformed

    // </editor-fold>  
    
    // <editor-fold defaultstate="collapsed" desc="Transfer Account Key Buttons">
    private void transAccKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey1ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "1";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey1ActionPerformed

    private void transAccKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey2ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "2";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey2ActionPerformed

    private void transAccKey3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey3ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "3";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey3ActionPerformed

    private void transAccKey4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey4ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "4";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey4ActionPerformed

    private void transAccKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey5ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "5";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey5ActionPerformed

    private void transAccKey6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey6ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "6";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey6ActionPerformed

    private void transAccKey7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey7ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "7";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey7ActionPerformed

    private void transAccKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey8ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "8";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey8ActionPerformed

    private void transAccKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey9ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "9";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey9ActionPerformed

    private void transAccKey0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKey0ActionPerformed
        // TODO add your handling code here:
        transferAccountNumber = transferAccountNumber+ "0";
        transferAccountField.setText(transferAccountNumber);
    }//GEN-LAST:event_transAccKey0ActionPerformed

    private void transAccKeyXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKeyXActionPerformed
        // TODO add your handling code here:
        if ("".equals(transferAccountNumber)){
            
        }else{
            transferAccountNumber = transferAccountNumber.substring(0, transferAccountNumber.length() - 1);
            transferAccountField.setText(transferAccountNumber);
        }
    }//GEN-LAST:event_transAccKeyXActionPerformed

    private void transAccKeyOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccKeyOKActionPerformed
        // TODO add your handling code here:
        transferMoney(transferAmountNumber, transferAccountNumber, balance);
    }//GEN-LAST:event_transAccKeyOKActionPerformed

    private void transAccBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transAccBackActionPerformed
        // TODO add your handling code here:
        TransferAmount.setVisible(true);
        TransferAccount.setVisible(false);
        transferAmountField.setText(transferAmountNumber);
    }//GEN-LAST:event_transAccBackActionPerformed

    
    // </editor-fold> 
    
    // </editor-fold>   
    
    // <editor-fold defaultstate="collapsed" desc="Functionalities">
    private void getReserve(){
        // THIS METHOD READS THE INTEGER IN THE FILE
        try (BufferedReader br = new BufferedReader(new FileReader("bankReserve.csv"))) {
            String line;
            // Read the CSV file line by line
            if ((line = br.readLine()) != null) {
                this.reserve = Integer.parseInt(line.trim());
                // Check if the first column (fruit) is "lemon"
            }
            br.close();
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void updateReserve(){
        
        try(BufferedWriter writer = new BufferedWriter(new FileWriter("bankReserve.csv"))){
            writer.write(String.valueOf(this.reserve));  // Convert the integer to a string and write it to the file
            writer.close();
            } catch (IOException e) {
                System.out.println("Error reading or writing to file: " + e.getMessage());
            }
    }
    private String dateTime(){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        LocalDateTime dateTimeNow = LocalDateTime.now();
        String currentDateTime = dateTimeNow.format(formatter);
        return currentDateTime;
    }
    private void transferMoney(String amountToTransfer, String accountRecepient, int balance){
        String rUsername = null;
        String rPassword = null;
        String rName = null;
        String rBirthdate = null;
        String rPhoneNumber = null;
        String rAddress = null;
        String rAccNumber = null;
        String rType = null;
        String rCard = null;
        String rPin = null;
        String rBalance = null;
        String currDateTime = dateTime();
        
        //FIND RECEPIENT IN DATABASE
        
         try (BufferedReader br = new BufferedReader(new FileReader("Accounts.csv"))) {
            String line;
            
            boolean found = false;
            // Read each line of the CSV file
            while ((line = br.readLine()) != null) {
                // Split the line into columns (name, age, number)
                String[] columns = line.split(",");

                // Check if the name in the CSV matches the user input
                if (columns[6].equalsIgnoreCase(accountRecepient)) {
                    found = true;
                    rUsername = columns[0];
                    rPassword = columns[1];
                    rName = columns[2];
                    rBirthdate = columns[3];
                    rPhoneNumber = columns[4];
                    rAddress = columns[5];
                    rAccNumber = columns[6];
                    rType = columns[7];
                    rCard = columns[8];
                    rPin = columns[9];
                    rBalance = columns[10];
                    break;
                }
            }

            // If no match is found, print a message
            if (!found) {
                JOptionPane.showMessageDialog(this, "Account number is not available", "Invalid Account Number", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        

        //SUBTRACT MONEY FROM SENDER ACCOUNT NUMBER
        int transferToInt = Integer.parseInt(amountToTransfer);
        if(balance < transferToInt){
            JOptionPane.showMessageDialog(this, "Cannot transfer money. Insufficient balance", "Insufficient Balance", JOptionPane.ERROR_MESSAGE);
            writeLine(username,password,name,birthdate,phoneNumber,address,accNumber,type,card,pin,balance);
            return;
        }
        balance = balance - transferToInt;
        deleteLine(accNumber);
        writeLine(username,password,name,birthdate,phoneNumber,address,accNumber,type,card,pin,balance);
        this.balance = balance;
        
        
        //ADD MONEY TO RECEPIENT ACCOUNT NUMBER
        int amtTransToInt = Integer.parseInt(amountToTransfer);
        int balRecepient = Integer.parseInt(rBalance);
        balRecepient = balRecepient + amtTransToInt;
        deleteLine(accountRecepient);
        writeLine(rUsername,rPassword,rName,rBirthdate,rPhoneNumber,rAddress,rAccNumber,rType,rCard,rPin,balRecepient);
        JOptionPane.showMessageDialog(this,  "₱" + amtTransToInt+" successfully transferred to account number: " + accountRecepient + "!");
        writeToTransaction(currDateTime,name, accNumber, amtTransToInt,"MONEY TRANSFER","Recepient Account: "+accountRecepient);
        returnToATMHome();
    }
    
    private void showCurrentBalance(int balance){
        String balanceDisplay = "₱" +Integer.toString(balance);
        DisplayBalance.setText(balanceDisplay);
    }
    private void withdraw(int balance){
        getReserve();
        String currDateTime = dateTime();
        int witToInt = Integer.parseInt(withdrawNumber);
        int reserveCheck = this.reserve + witToInt; // This line of code add the current reserve with the withdraw amount to compare if the withdraw amount will overflow the bank reserve
        
        if (reserveCheck > 1000000){
            JOptionPane.showMessageDialog(this, "Cannot withdraw money. Bank reserve will reach maximum capacity", "Bank Reserve Issue", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(balance < witToInt){
            JOptionPane.showMessageDialog(this, "Cannot withdraw money. Insufficient balance", "Insufficient Balance", JOptionPane.ERROR_MESSAGE);
            writeLine(username,password,name,birthdate,phoneNumber,address,accNumber,type,card,pin,balance);
            return;
        }
        balance = balance - witToInt;
        writeLine(username,password,name,birthdate,phoneNumber,address,accNumber,type,card,pin,balance);
        this.balance = balance;
        JOptionPane.showMessageDialog(this,  "₱" + witToInt+" successfully withdrew from account number: " + accNumber + "!");
        writeToTransaction(currDateTime,name, accNumber, witToInt,"WITHDRAW","Bank Transaction");
        
        this.reserve = reserve + witToInt;
        updateReserve();
        returnToATMHome(); 
    }
    
    private void deposit(int balance){
        String currDateTime = dateTime();
        int depToInt = Integer.parseInt(depositNumber);
        getReserve();
        if (this.reserve < depToInt){
            JOptionPane.showMessageDialog(this, "Cannot deposit money. Insufficient bank reserve", "Bank Reserve Issue", JOptionPane.ERROR_MESSAGE);
            return;
        }
        balance = balance + depToInt;
        this.balance = balance;
        writeLine(username,password,name,birthdate,phoneNumber,address,accNumber,type,card,pin,balance);
        JOptionPane.showMessageDialog(this,  "₱" + depToInt+" successfully deposited in account number: " + accNumber + "!");
        writeToTransaction(currDateTime,name, accNumber, depToInt,"DEPOSIT","Bank Transaction");
        
        this.reserve = reserve - depToInt;
        updateReserve();
        returnToATMHome(); 
    }
    
    private void writeLine(String username,
            String password,
            String name,
            String birthdate,
            String phoneNumber,
            String address,
            String accNumber,
            String type,
            String card,
            String pin,
            int balanceToDB){
        
         try (var writer = new BufferedWriter(new FileWriter("Accounts.csv", true))){
            writer.write(username + "," + password + "," + name + "," + birthdate + "," + phoneNumber + "," + address+ "," + accNumber + "," + type + "," + card + "," + pin + "," + balanceToDB);
            writer.newLine();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving to file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void writeToTransaction(String date, 
            String name, 
            String accNum, 
            int amount, 
            String action, 
            String description){
        try (var writer = new BufferedWriter(new FileWriter("Transactions.csv", true))){
            writer.write(date + "," + name + "," + accNum + "," + amount + "," + action + "," + description);
            writer.newLine();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving to file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void deleteLine(String accNum){
        File originalFile = new File("Accounts.csv");
        File tempFile = new File("accTemp.csv");

        boolean isRemoved = false;
        try (BufferedReader reader = new BufferedReader(new FileReader(originalFile));
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = reader.readLine()) != null) {
                // Check if the line contains the book ID
                if (line.contains(accNum)) {
                    isRemoved = true; // Mark as removed
                    continue; // Skip writing this line to the temp file
                }
                writer.write(line);
                writer.newLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error processing file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         // Replace the original file with the temp file
        if (isRemoved) {
            if (originalFile.delete()) {
                tempFile.renameTo(originalFile);
            } else {
                JOptionPane.showMessageDialog(this, "Error updating the file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            tempFile.delete(); // Cleanup temp file
        }
        
    }
    private void returnToPin(){
        PinWindow pin = new PinWindow();
        pin.setVisible(true);
        setVisible(false);
    }
    private void returnToATMHome(){
        ATMHomepage.setVisible(true);
        BalanceCheck.setVisible(false);
        DepositCash.setVisible(false);
        WithdrawCash.setVisible(false);
        TransferAmount.setVisible(false);
        TransferAccount.setVisible(false);
    }
    // </editor-fold> 
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ATMWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new ATMWindow().setVisible(true);
////            }
////        });
//    }
// <editor-fold defaultstate="collapsed" desc="VARIABLES">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ATMHomepage;
    private javax.swing.JButton BackWithdraw;
    private javax.swing.JPanel BalanceCheck;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonBalanceInquiry;
    private javax.swing.JButton ButtonDeposit;
    private javax.swing.JButton ButtonTransfer;
    private javax.swing.JButton ButtonWithdraw;
    private javax.swing.JLabel DepositBG;
    private javax.swing.JPanel DepositCash;
    private javax.swing.JLabel DisplayBalance;
    private javax.swing.JLabel HomepageBG;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton PrintBalance;
    private javax.swing.JPanel TransferAccount;
    private javax.swing.JPanel TransferAmount;
    private javax.swing.JLabel TransferBG;
    private javax.swing.JLabel TransferBG1;
    private javax.swing.JLabel WithdrawBG;
    private javax.swing.JPanel WithdrawCash;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton balanceBackButton;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton depKey0;
    private javax.swing.JButton depKey1;
    private javax.swing.JButton depKey2;
    private javax.swing.JButton depKey3;
    private javax.swing.JButton depKey4;
    private javax.swing.JButton depKey5;
    private javax.swing.JButton depKey6;
    private javax.swing.JButton depKey7;
    private javax.swing.JButton depKey8;
    private javax.swing.JButton depKey9;
    private javax.swing.JButton depKeyOK;
    private javax.swing.JButton depKeyX;
    private javax.swing.JButton depositBackButton;
    private javax.swing.JTextField depositField;
    private javax.swing.JPanel depositKeypad;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel keypadPanel;
    private javax.swing.JButton transAccBack;
    private javax.swing.JButton transAccKey0;
    private javax.swing.JButton transAccKey1;
    private javax.swing.JButton transAccKey2;
    private javax.swing.JButton transAccKey3;
    private javax.swing.JButton transAccKey4;
    private javax.swing.JButton transAccKey5;
    private javax.swing.JButton transAccKey6;
    private javax.swing.JButton transAccKey7;
    private javax.swing.JButton transAccKey8;
    private javax.swing.JButton transAccKey9;
    private javax.swing.JButton transAccKeyOK;
    private javax.swing.JButton transAccKeyX;
    private javax.swing.JPanel transAmntKeypad;
    private javax.swing.JButton transAmtBack;
    private javax.swing.JButton transAmtKey0;
    private javax.swing.JButton transAmtKey1;
    private javax.swing.JButton transAmtKey2;
    private javax.swing.JButton transAmtKey3;
    private javax.swing.JButton transAmtKey4;
    private javax.swing.JButton transAmtKey5;
    private javax.swing.JButton transAmtKey6;
    private javax.swing.JButton transAmtKey7;
    private javax.swing.JButton transAmtKey8;
    private javax.swing.JButton transAmtKey9;
    private javax.swing.JButton transAmtKeyOK;
    private javax.swing.JButton transAmtKeyX;
    private javax.swing.JTextField transferAccountField;
    private javax.swing.JPanel transferAccountKeypad;
    private javax.swing.JTextField transferAmountField;
    private javax.swing.JButton witKey0;
    private javax.swing.JButton witKey1;
    private javax.swing.JButton witKey2;
    private javax.swing.JButton witKey3;
    private javax.swing.JButton witKey4;
    private javax.swing.JButton witKey5;
    private javax.swing.JButton witKey6;
    private javax.swing.JButton witKey7;
    private javax.swing.JButton witKey8;
    private javax.swing.JButton witKey9;
    private javax.swing.JButton witKeyOK;
    private javax.swing.JButton witKeyX;
    private javax.swing.JTextField withdrawField;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
