/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankingmanagementsystem;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laurence
 */
public class AccountInformationView extends javax.swing.JFrame {

    /**
     * Creates new form USERACCOUNTAPPLICATION_ADMIN___
     */
    private String username;
    private String password;
    private int row;
    
    public AccountInformationView() {
//        String username, String password,String name,String birthdate,String phoneNumber,String address,int row
        initComponents();
//        this.username = username;
//        this.password = password;
//        nameLabel.setText(name);
//        birthLabel.setText(birthdate);
//        phoneLabel.setText(phoneNumber);
//        addressLabel.setText(address);
//        this.row = row;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overallPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        birhtDateLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        accNumDisplay = new javax.swing.JLabel();
        birthdayDisplay = new javax.swing.JLabel();
        phoneDisplay = new javax.swing.JLabel();
        windowTitleLabel = new javax.swing.JLabel();
        accNumLabel = new javax.swing.JLabel();
        typeDisplay = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameDisplay = new javax.swing.JLabel();
        addressDisplay = new javax.swing.JLabel();
        cardAvailLabel = new javax.swing.JLabel();
        typeDisplay1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BGLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overallPanel.setBackground(new java.awt.Color(0, 102, 153));
        overallPanel.setOpaque(false);
        overallPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name:");
        nameLabel.setPreferredSize(new java.awt.Dimension(112, 50));
        overallPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 120, 50));

        birhtDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        birhtDateLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        birhtDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        birhtDateLabel.setText("Birth Date:");
        birhtDateLabel.setPreferredSize(new java.awt.Dimension(175, 50));
        overallPanel.add(birhtDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 190, 50));

        phoneNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel.setText("Phone Number:");
        overallPanel.add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 270, 60));

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        overallPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 210, 80));

        accNumDisplay.setBackground(new java.awt.Color(255, 255, 255));
        accNumDisplay.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        accNumDisplay.setForeground(new java.awt.Color(255, 255, 255));
        accNumDisplay.setText("accnum");
        overallPanel.add(accNumDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 140, 50));

        birthdayDisplay.setBackground(new java.awt.Color(255, 255, 255));
        birthdayDisplay.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        birthdayDisplay.setForeground(new java.awt.Color(255, 255, 255));
        birthdayDisplay.setText("birthday");
        overallPanel.add(birthdayDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 290, 50));

        phoneDisplay.setBackground(new java.awt.Color(255, 255, 255));
        phoneDisplay.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        phoneDisplay.setForeground(new java.awt.Color(255, 255, 255));
        phoneDisplay.setText("phone");
        overallPanel.add(phoneDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 290, 50));

        windowTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        windowTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        windowTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        windowTitleLabel.setText("Account Information");
        overallPanel.add(windowTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 440, -1));

        accNumLabel.setBackground(new java.awt.Color(255, 255, 255));
        accNumLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        accNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        accNumLabel.setText("Bank Account Number:");
        overallPanel.add(accNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 410, 50));

        typeDisplay.setBackground(new java.awt.Color(255, 255, 255));
        typeDisplay.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        typeDisplay.setForeground(new java.awt.Color(255, 255, 255));
        typeDisplay.setText("type");
        overallPanel.add(typeDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 220, 50));

        typeLabel.setBackground(new java.awt.Color(255, 255, 255));
        typeLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Type of account:");
        overallPanel.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 290, 50));

        addressLabel.setBackground(new java.awt.Color(255, 255, 255));
        addressLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Address:");
        overallPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 150, 50));

        nameDisplay.setBackground(new java.awt.Color(255, 255, 255));
        nameDisplay.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        nameDisplay.setForeground(new java.awt.Color(255, 255, 255));
        nameDisplay.setText("name");
        overallPanel.add(nameDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 290, 50));

        addressDisplay.setBackground(new java.awt.Color(255, 255, 255));
        addressDisplay.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        addressDisplay.setForeground(new java.awt.Color(255, 255, 255));
        addressDisplay.setText("address");
        overallPanel.add(addressDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 350, 40));

        cardAvailLabel.setBackground(new java.awt.Color(255, 255, 255));
        cardAvailLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        cardAvailLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardAvailLabel.setText("Card Availability:");
        overallPanel.add(cardAvailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 300, 50));

        typeDisplay1.setBackground(new java.awt.Color(255, 255, 255));
        typeDisplay1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        typeDisplay1.setForeground(new java.awt.Color(255, 255, 255));
        typeDisplay1.setText("Available/Not Available");
        overallPanel.add(typeDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 290, 50));
        overallPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1470, 10));
        overallPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1470, 10));

        getContentPane().add(overallPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1390, 710));

        BGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.png"))); // NOI18N
        getContentPane().add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        // TODO add your handling code here:
        backButton.setContentAreaFilled(true);
        backButton.setForeground(Color.black);
        backButton.setBackground(Color.cyan);
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        // TODO add your handling code here:
        backButton.setContentAreaFilled(false);
        backButton.setForeground(Color.white);
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        returnToAdmin();
    }//GEN-LAST:event_backButtonActionPerformed

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="FUNCTIONALITIES">
    private void deleteAccountFromFile(int row){
        //THIS METHOD DECLINES THE APPLICATION OF THE USER. IT REMOVES ITS INFORMATION IN THE CSV
        String filePath = "AccountApplications.csv";  // Change to your CSV file path
        int rowToDelete = row; // Index of the row to delete (0-based index)

        // Read the CSV file into a List of Strings (rows)
        List<String> lines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                lines.add(line);  // Add each line to the list
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Remove the specific row (if it exists)
        if (rowToDelete >= 0 && rowToDelete < lines.size()) {
            lines.remove(rowToDelete); // Remove the row at the specified index
        } else {
            System.out.println("Row index is out of bounds.");
            return;
        }

        // Write the updated content back to the CSV file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(filePath))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();  // Write each line back into the file
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void refreshAccountTables(){
        AdminMain admin = new AdminMain();
        admin.setVisible(true);
        admin.loadAccountsForAccApplication("AccountApplications.csv");
    }
    
    private void accountApplicationWriteOnFile(String username,String password,String name,String birthdate,String phoneNumber,String address){
        //ADDS THE ACCOUNT TO ACCOUNT DATABASE
        try (var writer = new BufferedWriter(new FileWriter("Accounts.csv", true))){
            int accountNumber = RNGforAccountNumber();
            writer.write(username + "," + password + "," + name + "," + birthdate + "," + phoneNumber + "," + address+ "," + accountNumber + "," + "user" + "," + "no");
            writer.newLine();

            JOptionPane.showMessageDialog(this, "Account Verified!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving to file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private int RNGforAccountNumber(){
        Random random = new Random();
        // Generate a random 7-digit number
        int randomNumber = 10000000 + random.nextInt(90000); // Ensures the number is always 7 digits
        return randomNumber;
    }
    
    private void returnToAdmin(){
        AdminMain admin = new AdminMain();
        admin.setVisible(true);
        setVisible(false);
    }
    
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="MAIN(Nonfunctional)">
    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserAccountApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserAccountApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserAccountApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserAccountApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new UserAccountApplication().setVisible(true);
////            }
////        });
//
//    }
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="WIDGET VARIABLES">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JLabel accNumDisplay;
    private javax.swing.JLabel accNumLabel;
    private javax.swing.JLabel addressDisplay;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel birhtDateLabel;
    private javax.swing.JLabel birthdayDisplay;
    private javax.swing.JLabel cardAvailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel overallPanel;
    private javax.swing.JLabel phoneDisplay;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel typeDisplay;
    private javax.swing.JLabel typeDisplay1;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel windowTitleLabel;
    // End of variables declaration//GEN-END:variables
}
//</editor-fold>