package com.mycompany.bankingmanagementsystem;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Admin_Main extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Main
     */
    public Admin_Main() {
        initComponents();
        Dashboard.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        AccManagebutton = new javax.swing.JButton();
        Transactionsbutton = new javax.swing.JButton();
        Dashboardbutton = new javax.swing.JButton();
        AudRepbutton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        AccountManagement = new javax.swing.JPanel();
        Transactions = new javax.swing.JPanel();
        AuditAndReport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QuPAL BANKING ADMINISTRATOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 1000, 60));

        AccManagebutton.setForeground(new java.awt.Color(255, 255, 255));
        AccManagebutton.setText("ACCOUNT MANAGEMENT");
        AccManagebutton.setBorderPainted(false);
        AccManagebutton.setContentAreaFilled(false);
        AccManagebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccManagebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccManagebuttonMouseExited(evt);
            }
        });
        AccManagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccManagebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(AccManagebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 290, 80));

        Transactionsbutton.setForeground(new java.awt.Color(255, 255, 255));
        Transactionsbutton.setText("TRANSACTIONS");
        Transactionsbutton.setBorderPainted(false);
        Transactionsbutton.setContentAreaFilled(false);
        Transactionsbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransactionsbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransactionsbuttonMouseExited(evt);
            }
        });
        Transactionsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Transactionsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 290, 80));

        Dashboardbutton.setForeground(new java.awt.Color(255, 255, 255));
        Dashboardbutton.setText("DASHBOARD");
        Dashboardbutton.setBorderPainted(false);
        Dashboardbutton.setContentAreaFilled(false);
        Dashboardbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboardbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardbuttonMouseExited(evt);
            }
        });
        Dashboardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Dashboardbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 290, 80));

        AudRepbutton.setForeground(new java.awt.Color(255, 255, 255));
        AudRepbutton.setText("AUDIT AND REPORT");
        AudRepbutton.setBorderPainted(false);
        AudRepbutton.setContentAreaFilled(false);
        AudRepbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AudRepbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AudRepbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AudRepbuttonMouseExited(evt);
            }
        });
        AudRepbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudRepbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(AudRepbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 290, 80));

        jButton4.setText("DASHBOARD");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 290, 80));

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 630));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        Dashboard.setBackground(new java.awt.Color(51, 51, 255));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Timestamp", "Name", "Amount", "Type of Transactions", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Dashboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 268));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Action"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Dashboard.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 310, 360));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 860, 360));

        AccountManagement.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout AccountManagementLayout = new javax.swing.GroupLayout(AccountManagement);
        AccountManagement.setLayout(AccountManagementLayout);
        AccountManagementLayout.setHorizontalGroup(
            AccountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        AccountManagementLayout.setVerticalGroup(
            AccountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        Transactions.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout TransactionsLayout = new javax.swing.GroupLayout(Transactions);
        Transactions.setLayout(TransactionsLayout);
        TransactionsLayout.setHorizontalGroup(
            TransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        TransactionsLayout.setVerticalGroup(
            TransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        AuditAndReport.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout AuditAndReportLayout = new javax.swing.GroupLayout(AuditAndReport);
        AuditAndReport.setLayout(AuditAndReportLayout);
        AuditAndReportLayout.setHorizontalGroup(
            AuditAndReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        AuditAndReportLayout.setVerticalGroup(
            AuditAndReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AccountManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Transactions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AuditAndReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AccountManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Transactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AuditAndReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 1170, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardbuttonActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(true);
        AccountManagement.setVisible(false);
        Transactions.setVisible(false);
        AuditAndReport.setVisible(false);
    }//GEN-LAST:event_DashboardbuttonActionPerformed

    private void DashboardbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardbuttonMouseEntered
        // TODO add your handling code here:
        Dashboardbutton.setContentAreaFilled(true);
        Dashboardbutton.setBackground(Color.cyan);
        Dashboardbutton.setForeground(Color.black);
    }//GEN-LAST:event_DashboardbuttonMouseEntered

    private void DashboardbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardbuttonMouseExited
        // TODO add your handling code here:
        Dashboardbutton.setContentAreaFilled(false);
        Dashboardbutton.setForeground(Color.white);
    }//GEN-LAST:event_DashboardbuttonMouseExited

    private void DashboardbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardbuttonMouseClicked

    private void AccManagebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccManagebuttonMouseEntered
        // TODO add your handling code here:
        AccManagebutton.setContentAreaFilled(true);
        AccManagebutton.setBackground(Color.cyan);
        AccManagebutton.setForeground(Color.black);
    }//GEN-LAST:event_AccManagebuttonMouseEntered

    private void AccManagebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccManagebuttonMouseExited
        // TODO add your handling code here:
        AccManagebutton.setContentAreaFilled(false);
        AccManagebutton.setForeground(Color.white);
    }//GEN-LAST:event_AccManagebuttonMouseExited

    private void TransactionsbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsbuttonMouseEntered
        // TODO add your handling code here:
        Transactionsbutton.setContentAreaFilled(true);
        Transactionsbutton.setBackground(Color.cyan);
        Transactionsbutton.setForeground(Color.black);
    }//GEN-LAST:event_TransactionsbuttonMouseEntered

    private void TransactionsbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsbuttonMouseExited
        // TODO add your handling code here:
        Transactionsbutton.setContentAreaFilled(false);
        Transactionsbutton.setForeground(Color.white);
    }//GEN-LAST:event_TransactionsbuttonMouseExited

    private void AudRepbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudRepbuttonMouseEntered
        // TODO add your handling code here:
        AudRepbutton.setContentAreaFilled(true);
        AudRepbutton.setBackground(Color.cyan);
        AudRepbutton.setForeground(Color.black);
    }//GEN-LAST:event_AudRepbuttonMouseEntered

    private void AudRepbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudRepbuttonMouseExited
        // TODO add your handling code here:
        AudRepbutton.setContentAreaFilled(false);
        AudRepbutton.setForeground(Color.white);
    }//GEN-LAST:event_AudRepbuttonMouseExited

    private void AccManagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccManagebuttonActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        AccountManagement.setVisible(true);
        Transactions.setVisible(false);
        AuditAndReport.setVisible(false);
    }//GEN-LAST:event_AccManagebuttonActionPerformed

    private void TransactionsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsbuttonActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        AccountManagement.setVisible(false);
        Transactions.setVisible(true);
        AuditAndReport.setVisible(false);
    }//GEN-LAST:event_TransactionsbuttonActionPerformed

    private void AudRepbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudRepbuttonActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        AccountManagement.setVisible(false);
        Transactions.setVisible(false);
        AuditAndReport.setVisible(true);
    }//GEN-LAST:event_AudRepbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccManagebutton;
    private javax.swing.JPanel AccountManagement;
    private javax.swing.JButton AudRepbutton;
    private javax.swing.JPanel AuditAndReport;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton Dashboardbutton;
    private javax.swing.JPanel Transactions;
    private javax.swing.JButton Transactionsbutton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
